-------------------------------------------------------------------------------
Test set: ProductDetails
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 42.384 s <<< FAILURE! - in ProductDetails
User is click on the Product and check the Product Details(ProductDetails)  Time elapsed: 42.384 s  <<< ERROR!
org.openqa.selenium.NoSuchSessionException: 
invalid session id
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ASUS', ip: '192.168.1.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.114, chrome: {chromedriverVersion: 91.0.4472.101 (af52a90bf870..., userDataDir: C:\Users\REENA\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:57798}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 5a8f797bfff6f28cae9692d23ed70c45

User is click on the Product and check the Product Details(ProductDetails)  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException

User is click on the Product and check the Product Details(ProductDetails)  Time elapsed: 0 s  <<< ERROR!
org.openqa.selenium.WebDriverException: 
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:37567
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ASUS', ip: '192.168.1.104', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_191'
Driver info: driver.version: RemoteWebDriver
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:37567
Caused by: java.net.ConnectException: Connection refused: connect

